### ISSUE TITLE
Missing navbar-transparent.html

### ISSUE THREAD

**Issue by mvcf10** [timcreative/material-kit#11]
Missing navbar-transparent.html.
This error was detected at page: components-documentation.html#navbar-row

**Comment by alexandru-paduraru** [comment]
@mvcf10 thank you for pointing out. We will add it in the next update. You can see the example with the transparent navbar which is getting a color on scroll on this example -> http://demos.creative-tim.com/material-kit/examples/profile-page.html. You also have that page inside the archive that you downloaded.

Please let us know if we can help you with anything else.

Best,
Alex

**Comment by alexandru-paduraru** [comment]
Thank you for the information. Fixed in v1.0.1

Best,
Alex
