### ISSUE TITLE
Toggle component is missing <span class="toggle"> in components documentation

### ISSUE THREAD

**Issue by Tech720** [timcreative/material-kit#12]
The code for the Toggle component appears to be missing the need for the `<span class="toggle">` within the `<label>` tag.

Current code listed in components:
`<div class="togglebutton">
	<label>
    	<input type="checkbox" checked="">
		Toggle is on
	</label>
</div>`

Should be:
`<div class="togglebutton">
	<label>
    	<input type="checkbox" checked=""><span class="toggle"></span>
		Toggle is on
	</label>
</div>`

Correct?

**Comment by alexandru-paduraru** [comment]
@Tech720 thank you for pointing out. No, you don't need to add the **<span class="toggle"></span>** because that is added automatically from the javascript so you have to write less HTML when you write a toggle. 

Please let us know if we can help with anything else.

Best,
Alex
