### ISSUE TITLE
Issue with Checkbox Animation

### ISSUE THREAD

**Issue by duskykmh** [timcreative/material-kit#17]
On click for check or uncheck on either of the 2 clickable boxes, the animation bubble appears much lower than it should.

Using Firefox 46.0.1

**Comment by alexandru-paduraru** [comment]
@duskykmh bug confirmed on Firefox. Thank you for the information. We will update it in the next release. 

Best, Alex!

**Comment by alexandru-paduraru** [comment]
Thank you for the information. Fixed in v1.0.1

Best,
Alex

**Comment by alexandru-paduraru** [comment]
tesr from zube
