### ISSUE TITLE
Navbar Issue

### ISSUE THREAD

**Issue by aykut78** [timcreative/material-kit#18]
Navbars with dropdowns have wrong height size:
![screenshot_2016-06-14-21-06-55](https://cloud.githubusercontent.com/assets/14788425/16089944/b3dbd8d6-332d-11e6-9a3a-bcb98f099e7f.png)
![screenshot_2016-06-14-20-51-53](https://cloud.githubusercontent.com/assets/14788425/16089931/a470db58-332d-11e6-8935-ff6669a12fcc.png)
![screenshot_2016-06-14-21-07-06](https://cloud.githubusercontent.com/assets/14788425/16089945/b60f8d3c-332d-11e6-9fe1-67049ac7cf4e.png)

**Comment by alexandru-paduraru** [comment]
Thank you for the information. Fixed in v1.0.1

Best,
Alex
