### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by GijsGoudzwaard** [timcreative/material-kit#28]
What browsers ( / versions) are supported?

**Comment by alexandru-paduraru** [comment]
@GijsGoudzwaard the product is based on Bootstrap, so all the browsers that they support including Chrome, Firefox, Edge, Safari etc. are supported by us too. They also provide support for IE 9, 10 and 11. There are high chances that our product to work fine on IE 9, 10 but we are not supporting those browsers anymore. Microsoft stops their support for those old browsers and we are doing the same.

Best,
Alex
