### ISSUE TITLE
bootstrap-select

### ISSUE THREAD

**Issue by sldobri** [timcreative/material-kit#3]
Like:
https://silviomoreto.github.io/bootstrap-select/examples/

**Comment by rafaeldev** [comment]
Or like this:
http://fezvrasta.github.io/bootstrap-material-design/#dropdown-menu

**Comment by alexandru-paduraru** [comment]
@sldobri thank you for the suggestion. I think we will use @rafaeldev's example because Material Kit was built over Bootstrap Material Design of Fezvrasta. Right now we are working for the PRO version of this kit then after we release it we will add the select in the Free version too.

Best,
Alex

**Comment by uhfath** [comment]
Has this made into free version?

**Comment by alexandru-paduraru** [comment]
@uhfath bootstrap Select is a plugin that is included only in Material Kit PRO.

**Comment by uhfath** [comment]
Thanks for the info.
