### ISSUE TITLE
Only one slider per page working

### ISSUE THREAD

**Issue by sjoshi804** [timcreative/material-kit#4]
When you try to add more than one slider to a page, only the first appears. For some reason the id for a slider must = "sliderRegular" for it to work

**Comment by alexandru-paduraru** [comment]
@sjoshi804 please check the [Documentation - Section Sliders](http://demos.creative-tim.com/material-kit/components-documentation.html#sliders-row) and you will see that each slider needs an id and needs to be called separate using the javascript plugin "**noUiSlider**"

All the best,
Alex
