### ISSUE TITLE
Add install with npm option

### ISSUE THREAD

**Issue by gon250** [timcreative/material-kit#45]
Add install with npm option

**Comment by alexandru-paduraru** [comment]
@gon250 thank you for the suggestion. We will add the npm option soon!

**Comment by gon250** [comment]
Thank you!

Most of the people I know only use npm and are removing bower from their projects, so would be a great thing add it to npm. 

btw what do you think about convert the js code to ts code? Would be great for the people who use angular 2.

**Comment by alexandru-paduraru** [comment]
@gon250 got it! For the TS we didn't think yet but we have in plan to convert our products to Angular2

**Comment by gon250** [comment]
@alexandru-paduraru cool, so just update the readme file and would be perfect. 👍
