### ISSUE TITLE
License is useless

### ISSUE THREAD

**Issue by nemequ** [timcreative/material-kit#48]
***IANAL***

I was thinking about using this for an open-source project (AGPLv3 back-end, not sure what to do about the front-end yet), but the licensing is far too ambiguous.  Without the GPL exceptions (I'll get to that), the license is pretty clearly non-free.  It forbids redistribution, and derivative works are questionable at best.

The rights and restrictions sections seem contradictory; apparently people are allowed to "use" the theme, but not redistribute it.  Since this visiting a web site which uses a them triggers redistribution, I guess it's only possible to look at your own creation, but not actually make it available on the web.

Interestingly, the document doesn't appear to actually grant any license whatsoever; it merely describes the conditions for whichever license (personal or developer) was purchased.  Are you trying to grant a personal license, a developer license, or neither?

There are no definitions for important terms like "item" or "resource".  I really have no idea how all this applies to either material-kit or anything using it… is the item material-kit, or the combination of material-kit and the project using it, or part of material-kit (like the JS or CSS)?  The license even seems to try to treat material-kit as a single work, and the personal license specifically forbids breaking it up, but there are at least two files (one CSS and one JS) which *must* be kept separate to work correctly.

It seems like anyone using this project is relying on the good faith of the copyright holders rather than the license.  While I do believe in that good faith (i.e., I don't think you'll go around filing lawsuits against people who use this for a blog or something), it would be very irresponsible to take the risk, which brings me to the GPL stuff:

> If the item was created using materials which are the subject of a GNU General Public Li-
cense (GPL), your use of the item is subject to the terms of the GPL in place of the foregoing
conditions (to the extent the GPL applies).

AFAICT, you're trying to allow GPL'd projects to use material-kit under the terms of the GPL instead of your license, which is great.

First off, "a GNU General Public License" *could* quite reasonably be interpreted to mean the Lesser GPL (v2.1 or 3), Library GPL, GNU Affero GPL in addition to the "main" GPLv1/2/3.  It would probably be a good idea to borrow some language from the [FSF's suggested notice](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html#SEC4).

What is the "item" here?  Is it material-kit, or the combined work created by merging material-kit with the code using it?  It seems like you want it to mean the latter the second time you use "item", but that doesn't really make sense for the first use.  AFAICT, the only consistent reading is the former, which would mean the entire amalgamated project must be "subject to the terms of the GPL".  In that case, every project actually using this is violating the license… bootstrap is MIT licensed.  You're free to include MIT-licensed code like bootstrap in a GPL (or proprietary) project, but that doesn't change its license to GPL (and, since you don't own the copyright, you have no right to do so).  That means there is no way to comply with the license.

The common way to do this is dual-licensing; allow people to use material-kit under the terms of the GPL *or* purchase a license from you so they can use it in proprietary code.  I suggest you consider doing that instead of saying everything has to be GPL'd.

Even with dual-licensing, there are a lot of issues with using the GPL for something like this.  The obvious one is whether running GPL'd javascript code in a non-GPL-compatible browser is even allowed, which is a question I don't think has ever been resolved.  The FSF's stance about [running non-GPL code in a GPL interpreter](https://www.gnu.org/licenses/gpl-faq.html#IfInterpreterIsGPL) seems to indicate that it's not, but of course that's not legally binding…

So, my reading of this is basically

 * There is no actual grant of a personal or developer license.
 * Even if there were, those licenses are ambiguous and contain contradictory provisions.
 * It's impossible to comply with the conditions for using this under the terms of the GPL (at least without rewriting bootstrap and releasing that under the GPL, in addition to anything else I may want to use such as jquery, font awesome, web fonts, etc.).
 * Even if I could get all material-kit's code under "the" GPL, I would still have some pretty major reservations, but that's really a separate issue.

**Comment by alexandru-paduraru** [comment]
@nemequ thank you for your interest in our product. We have in plan to upgrade our licensing to MIT in the next weeks, in order for everybody to feel safe when they use this product. Till now we didn't have any issues regarding the licenses, people understood that they can use the product with a Personal License from our website: http://www.creative-tim.com/product/material-kit for their personal projects or startups or for a client and they need a Developer License if they want to use the product for multiple clients or for themes/templates.

You can use it in your open source project as long as you keep the copyright part of the CSS/JS.

Please let us know if we can help you with anything else.

All the best,
Alex

Managing Partner @Creative-Tim.com
