### ISSUE TITLE
Sidebar issue

### ISSUE THREAD

**Issue by r0mk1n** [timcreative/material-kit#5]
On components page in compact mode ( small or extra-small ) sidebar should mot be fixed at top

![components](https://cloud.githubusercontent.com/assets/406895/14408414/fb1f07c8-fefc-11e5-96f6-e907dc9e8102.png)

**Comment by alexandru-paduraru** [comment]
@r0mk1n thank you for poiting out. We will fix this issue in the next update.

All the best,
Alex

**Comment by alexandru-paduraru** [comment]
Thank you for the information. Fixed in v1.0.1

Best,
Alex
