### ISSUE TITLE
Is this compatible with React Bootstrap?

### ISSUE THREAD

**Issue by chris-herring** [timcreative/material-kit#52]
Is this compatible with React Bootstrap? [(https://react-bootstrap.github.io)](https://react-bootstrap.github.io)

**Comment by alexandru-paduraru** [comment]
@chris-herring thank you for your interest in our product. Sincerely we didn't test our product with React Bootstrap so we cannot tell you if it is compatible or not. Did you test that yet? you can try to integrate it in React and let us know what issues you've got and maybe we can help you.

Best,
Alex

**Comment by chris-herring** [comment]
Hi Alex,

Thanks for the reply. I like the look of your product but I can't invest the time atm to work on React integration. 

Thanks
Chris

**Comment by alexandru-paduraru** [comment]
@chris-herring no worries, we keep this in mind and after we finish to migrate all our products to Angular 2 we can start with React :D 

Best,
Alex
